//Cities
export const FETCH_ALL_CITIES = 'FETCH_ALL_CITIES';
export const FETCH_SINGLE_CITY = 'FETCH_SINGLE_CITY';

//Itineraries
export const FETCH_ITINERARIES_FOR_A_CITY = 'FETCH_ITINERARIES_FOR_A_CITY';

//Users
export const CREATE_USER = 'CREATE_USER';